language: c

sudo: false

git:
  depth: 1

compiler:
  - gcc
  - clang
  - msvc

os:
  - linux
  - osx
  - windows

addons:
  apt:
    update: true
    packages:
      - libcunit1
      - libcunit1-dev
  homebrew:
    update: true # one needs to update brew.
    packages:
      - cunit

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ./bin/unit-test

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
#        update: true
        packages:
          - libcunit1
          - libcunit-dev
  - os: linux
    compiler: clang 
    addons:
      apt:
#        update: true
        packages:
          - libcunit1
          - libcunit-dev
  - os: osx
    compiler: clang
    addons:
      homebrew:
        update: true
        packages:
          - cunit
