language:
    - C
    - C++

sudo: false

git:
    depth: 1

os:
    - linux
    - windows

addons:
    apt:
        update: true
        packages:
            - libcunit1
            - libcunit1-dev

script:
    - cmake . -DCMAKE_BUILD_TYPE=Release
    - cmake --build . -- || cmake --build Release --
