language: c

sudo: false

git:
  depth: 1

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIT_TESTS=OFF
  - cmake --build .
  - cpack

jobs:
  include:
  - os: linux
    compiler: gcc
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release
      - cmake --build .
      - ./bin/unit-test
      - cpack
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: linux
    compiler: clang 
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release
      - cmake --build .
      - ./bin/unit-test
      # don't run cpack use the gcc version
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: osx
    compiler: clang
  - os: windows
