language: c

sudo: false

git:
  depth: 1

jobs:
  include:
  - os: linux
    compiler: gcc
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release
      - cmake --build .
      - ./bin/unit-test
      - cpack -G DEB
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: linux
    compiler: clang 
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release
      - cmake --build .
      - ./bin/unit-test
      # don't run cpack use the gcc version
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: osx
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIT_TESTS=OFF
      - cmake --build .
      - cpack
  - os: windows
    addons:
      chocolatey:
        packages:
          - nsis
        
    script:
      - cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIT_TESTS=OFF
      - cmake --build .
      - cpack -G NSIS64
