language:
    - C
    - C++

sudo: false

git:
    depth: 1

os:
    - linux
    - windows
    - osx

addons:
    apt:
        packages:
            - libcunit1
            - libcunit1-dev
    homebrew:
        packages:
            - cunit
#    chocolatey:
#        packages:
#            # - libcunit
        

script:
    - cmake . 
    - cmake --build . -- 
    - ./bin/unit-test
