language: c

sudo: false

git:
  depth: 1

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ./bin/unit-test

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: linux
    compiler: clang 
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: osx
    compiler: clang
    addons:
      homebrew:
        update: true
        packages:
          - cunit
    cache:
        directories:
            - $HOME/Library/Caches/Homebrew
    before_cache:
        - brew cleanup
  - os: windows
#    before_script:
#      - wget https://github.com/lelegard/CUnit-msvc/releases/download/v2.1-3/CUnit-msvc-2.1-3.exe
#       - ./CUnit-msvc-2.1-3.exe /S
    script:
      # disable unit test until we have a way of installing CUnit
      - cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIT_TESTS=OFF
      - cmake --build .
# if we don't build the test, don't run them
#      - ./bin/unit-test

