language:
    - C
    - C++

# sudo: false

git:
    depth: 1

os:
    - linux
#    - windows
#    - osx

addons:
    apt:
#        update: true
        packages:
            - libcunit1
            - libcunit1-dev
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
            - wine
#    homebrew:
#        update: true # one needs to update brew.
#        packages:
#            - cunit


script:
    - mkdir linux
    - mkdir windows
    - cd linux
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ./bin/unit-test
    - cd $OLDPWD
    - cd windows
    - CC=gcc-mingw-w64-i686 CXX=g++-mingw-w64-i686
    - LDFLAGS="-static-libgcc -static-libstdc++"
    - cmake .. -DCMAKE_BUILD_TYPE=Release 

