language:
    - C
    - C++

sudo: false

git:
    depth: 1

os:
    - linux
    - windows

addons:
    apt:
        update: true
        packages:
            - libcunit1
            - libcunit1-dev

script:
    - cmake .
    - cmake --build . -- || cmake --build debug --
