language: c

sudo: false

git:
  depth: 1

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ./bin/unit-test

jobs:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: linux
    compiler: clang 
    addons:
      apt:
        update: true
        packages:
          - libcunit1
          - libcunit1-dev
  - os: osx
    compiler: clang
    addons:
      homebrew:
        update: true
        packages:
          - cunit
